// src/views/pages/auth/LoginV2.jsx
'use client';

// React Imports
import { useState } from 'react';

// Next Imports
import Link from 'next/link';

// MUI Imports
import useMediaQuery from '@mui/material/useMediaQuery';
import { styled, useTheme } from '@mui/material/styles';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import InputAdornment from '@mui/material/InputAdornment';
import Checkbox from '@mui/material/Checkbox';
import Button from '@mui/material/Button';
import FormControlLabel from '@mui/material/FormControlLabel';
import Divider from '@mui/material/Divider';

// Third-party Imports
import classnames from 'classnames';

// Component Imports
import Logo from '@components/layout/shared/Logo';
import CustomTextField from '@core/components/mui/TextField';

// Config Imports
import themeConfig from '@configs/themeConfig';

// Hook Imports
import { useImageVariant } from '@core/hooks/useImageVariant';
import { useSettings } from '@core/hooks/useSettings';

// Styled Custom Components
const LoginIllustration = styled('img')(({ theme }) => ({
    zIndex: 2,
    blockSize: 'auto',
    maxBlockSize: 680,
    maxInlineSize: '100%',
    margin: theme.spacing(0),
    [theme.breakpoints.down(1536)]: {
        maxBlockSize: 550
    },
    [theme.breakpoints.down('lg')]: {
        maxBlockSize: 450
    }
}));

const MaskImg = styled('img')({
    blockSize: 'auto',
    maxBlockSize: 355,
    inlineSize: '100%',
    position: 'absolute',
    insetBlockEnd: 0,
    zIndex: -1
});

const LoginV2 = ({ mode }) => {
    // States
    const [isPasswordShown, setIsPasswordShown] = useState(false);

    // Vars
    const darkImg = '/images/pages/auth-mask-dark.png';
    const lightImg = '/images/pages/auth-mask-light.png';
    const darkIllustration = '/images/illustrations/auth/v2-login-dark.png';
    const lightIllustration = '/images/illustrations/auth/v2-login-light.png';
    const borderedDarkIllustration = '/images/illustrations/auth/v2-login-dark-border.png';
    const borderedLightIllustration = '/images/illustrations/auth/v2-login-light-border.png';

    // Hooks
    const { settings } = useSettings();
    const theme = useTheme();
    const hidden = useMediaQuery(theme.breakpoints.down('md'));
    const authBackground = useImageVariant(mode, lightImg, darkImg);

    const characterIllustration = useImageVariant(
        mode,
        lightIllustration,
        darkIllustration,
        borderedLightIllustration,
        borderedDarkIllustration
    );

    const handleClickShowPassword = () => setIsPasswordShown((show) => !show);

    return (
        <div className="flex bs-full justify-center">
            <div
                className={classnames('flex bs-full items-center justify-center flex-1 relative max-md:hidden', {
                    'border-ie': settings.skin === 'bordered'
                })}
            >
                <LoginIllustration src={characterIllustration} alt="character-illustration" />
                {!hidden && (
                    <MaskImg
                        alt="mask"
                        src={authBackground}
                        className={classnames({ 'scale-x-[-1]': theme.direction === 'rtl' })}
                    />
                )}
            </div>
            <div className="flex justify-center items-center bs-full bg-backgroundPaper min-is-full! p-6 md:min-is-[unset]! md:p-12 md:is-[480px]">
                <Link
                    href={'/'}
                    className="absolute block-start-5 sm:block-start-[33px] inline-start-6 sm:start-[38px]"
                >
                    <Logo />
                </Link>
                <div className="flex flex-col gap-6 is-full sm:is-auto md:is-full sm:max-is-[400px] md:max-is-[unset] mbs-11 sm:mbs-14 md:mbs-0">
                    <div className="flex flex-col gap-1">
                        <Typography variant="h4">{`Welcome to ${themeConfig.templateName}! 👋🏻`}</Typography>
                        <Typography>Please sign-in to your account and start the adventure</Typography>
                    </div>
                    <form
                        noValidate
                        autoComplete="off"
                        onSubmit={(e) => e.preventDefault()}
                        className="flex flex-col gap-6"
                    >
                        <CustomTextField
                            autoFocus
                            fullWidth
                            label="Email or Username"
                            placeholder="Enter your email or username"
                        />
                        <CustomTextField
                            fullWidth
                            label="Password"
                            placeholder="············"
                            id="outlined-adornment-password"
                            type={isPasswordShown ? 'text' : 'password'}
                            slotProps={{
                                input: {
                                    endAdornment: (
                                        <InputAdornment position="end">
                                            <IconButton
                                                edge="end"
                                                onClick={handleClickShowPassword}
                                                onMouseDown={(e) => e.preventDefault()}
                                            >
                                                <i className={isPasswordShown ? 'tabler-eye-off' : 'tabler-eye'} />
                                            </IconButton>
                                        </InputAdornment>
                                    )
                                }
                            }}
                        />
                        <div className="flex justify-between items-center gap-x-3 gap-y-1 flex-wrap">
                            <FormControlLabel control={<Checkbox />} label="Remember me" />
                            <Typography
                                className="text-end"
                                color="primary.main"
                                component={Link}
                                href={'/pages/auth/forgot-password-v2'}
                            >
                                Forgot password?
                            </Typography>
                        </div>
                        <Button fullWidth variant="contained" type="submit">
                            Login
                        </Button>
                        <div className="flex justify-center items-center flex-wrap gap-2">
                            <Typography>New on our platform?</Typography>
                            <Typography component={Link} href={'/pages/auth/register-v2'} color="primary.main">
                                Create an account
                            </Typography>
                        </div>
                        <Divider className="gap-2 text-textPrimary">or</Divider>
                        <div className="flex justify-center items-center gap-1.5">
                            <IconButton className="text-facebook" size="small">
                                <i className="tabler-brand-facebook-filled" />
                            </IconButton>
                            <IconButton className="text-twitter" size="small">
                                <i className="tabler-brand-twitter-filled" />
                            </IconButton>
                            <IconButton className="text-textPrimary" size="small">
                                <i className="tabler-brand-github-filled" />
                            </IconButton>
                            <IconButton className="text-error" size="small">
                                <i className="tabler-brand-google-filled" />
                            </IconButton>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default LoginV2;

// vuexy-admin-v10.11.1/nuxt-version/javascript-version/full-version/pages/pages/authentication/login-v2.vue
<script setup>
import AuthProvider from '@/views/pages/authentication/AuthProvider.vue'
import { useGenerateImageVariant } from '@core/composable/useGenerateImageVariant'
import authV2LoginIllustrationBorderedDark from '@images/pages/auth-v2-login-illustration-bordered-dark.png'
import authV2LoginIllustrationBorderedLight from '@images/pages/auth-v2-login-illustration-bordered-light.png'
import authV2LoginIllustrationDark from '@images/pages/auth-v2-login-illustration-dark.png'
import authV2LoginIllustrationLight from '@images/pages/auth-v2-login-illustration-light.png'
import authV2MaskDark from '@images/pages/misc-mask-dark.png'
import authV2MaskLight from '@images/pages/misc-mask-light.png'
import { VNodeRenderer } from '@layouts/components/VNodeRenderer'
import { themeConfig } from '@themeConfig'

definePageMeta({
  layout: 'blank',
  public: true,

})

const form = ref({
  email: '',
  password: '',
  remember: false,
})

const isPasswordVisible = ref(false)
const authThemeImg = useGenerateImageVariant(authV2LoginIllustrationLight, authV2LoginIllustrationDark, authV2LoginIllustrationBorderedLight, authV2LoginIllustrationBorderedDark, true)
const authThemeMask = useGenerateImageVariant(authV2MaskLight, authV2MaskDark)
</script>

<template>
  <NuxtLink to="/">
    <div class="auth-logo d-flex align-center gap-x-3">
      <VNodeRenderer :nodes="themeConfig.app.logo" />
      <h1 class="auth-title">
        {{ themeConfig.app.title }}
      </h1>
    </div>
  </NuxtLink>

  <VRow
    no-gutters
    class="auth-wrapper bg-surface"
  >
    <VCol
      md="8"
      class="d-none d-md-flex"
    >
      <div class="position-relative bg-background w-100 me-0">
        <div
          class="d-flex align-center justify-center w-100 h-100"
          style="padding-inline: 6.25rem;"
        >
          <VImg
            max-width="613"
            :src="authThemeImg"
            class="auth-illustration mt-16 mb-2"
          />
        </div>

        <img
          class="auth-footer-mask flip-in-rtl"
          :src="authThemeMask"
          alt="auth-footer-mask"
          height="280"
          width="100"
        >
      </div>
    </VCol>

    <VCol
      cols="12"
      md="4"
      class="auth-card-v2 d-flex align-center justify-center"
    >
      <VCard
        flat
        :max-width="500"
        class="mt-12 mt-sm-0 pa-6"
      >
        <VCardText>
          <h4 class="text-h4 mb-1">
            Welcome to <span class="text-capitalize">{{ themeConfig.app.title }}</span>! 👋🏻
          </h4>
          <p class="mb-0">
            Please sign-in to your account and start the adventure
          </p>
        </VCardText>
        <VCardText>
          <VForm @submit.prevent="() => {}">
            <VRow>
              <!-- email -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.email"
                  autofocus
                  label="Email or Username"
                  type="email"
                  placeholder="johndoe@email.com"
                />
              </VCol>

              <!-- password -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.password"
                  label="Password"
                  placeholder="············"
                  :type="isPasswordVisible ? 'text' : 'password'"
                  autocomplete="password"
                  :append-inner-icon="isPasswordVisible ? 'tabler-eye-off' : 'tabler-eye'"
                  @click:append-inner="isPasswordVisible = !isPasswordVisible"
                />

                <div class="d-flex align-center flex-wrap justify-space-between my-6">
                  <VCheckbox
                    :id="useId()"
                    v-model="form.remember"
                    label="Remember me"
                  />
                  <NuxtLink
                    class="text-primary"
                    :to="{ name: 'pages-authentication-forgot-password-v2' }"
                  >
                    Forgot Password?
                  </NuxtLink>
                </div>

                <VBtn
                  block
                  type="submit"
                >
                  Login
                </VBtn>
              </VCol>

              <!-- create account -->
              <VCol
                cols="12"
                class="text-body-1 text-center"
              >
                <span class="d-inline-block">
                  New on our platform?
                </span>
                <NuxtLink
                  class="text-primary ms-1 d-inline-block text-body-1"
                  :to="{ name: 'pages-authentication-register-v2' }"
                >
                  Create an account
                </NuxtLink>
              </VCol>

              <VCol
                cols="12"
                class="d-flex align-center"
              >
                <VDivider />
                <span class="mx-4">or</span>
                <VDivider />
              </VCol>

              <!-- auth providers -->
              <VCol
                cols="12"
                class="text-center"
              >
                <AuthProvider />
              </VCol>
            </VRow>
          </VForm>
        </VCardText>
      </VCard>
    </VCol>
  </VRow>
</template>

<style lang="scss">
@use "@core/scss/template/pages/page-auth";
</style>
