// src/views/pages/auth/LoginV1.jsx
'use client';

// React Imports
import { useState } from 'react';

// Next Imports
import Link from 'next/link';

// MUI Imports
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import InputAdornment from '@mui/material/InputAdornment';
import Checkbox from '@mui/material/Checkbox';
import Button from '@mui/material/Button';
import FormControlLabel from '@mui/material/FormControlLabel';
import Divider from '@mui/material/Divider';

// Component Imports
import Logo from '@components/layout/shared/Logo';
import CustomTextField from '@core/components/mui/TextField';

// Config Imports
import themeConfig from '@configs/themeConfig';

// Styled Component Imports
import AuthIllustrationWrapper from './AuthIllustrationWrapper';

const LoginV1 = () => {
    // States
    const [isPasswordShown, setIsPasswordShown] = useState(false);

    // Hooks
    const handleClickShowPassword = () => setIsPasswordShown((show) => !show);

    return (
        <AuthIllustrationWrapper>
            <Card className="flex flex-col sm:is-[450px]">
                <CardContent className="sm:!p-12">
                    <Link href={'/'} className="flex justify-center mbe-6">
                        <Logo />
                    </Link>
                    <div className="flex flex-col gap-1 mbe-6">
                        <Typography variant="h4">{`Welcome to ${themeConfig.templateName}! 👋🏻`}</Typography>
                        <Typography>Please sign-in to your account and start the adventure</Typography>
                    </div>
                    <form
                        noValidate
                        autoComplete="off"
                        onSubmit={(e) => e.preventDefault()}
                        className="flex flex-col gap-6"
                    >
                        <CustomTextField
                            autoFocus
                            fullWidth
                            label="Email or Username"
                            placeholder="Enter your email or username"
                        />
                        <CustomTextField
                            fullWidth
                            label="Password"
                            placeholder="············"
                            id="outlined-adornment-password"
                            type={isPasswordShown ? 'text' : 'password'}
                            slotProps={{
                                input: {
                                    endAdornment: (
                                        <InputAdornment position="end">
                                            <IconButton
                                                edge="end"
                                                onClick={handleClickShowPassword}
                                                onMouseDown={(e) => e.preventDefault()}
                                            >
                                                <i className={isPasswordShown ? 'tabler-eye-off' : 'tabler-eye'} />
                                            </IconButton>
                                        </InputAdornment>
                                    )
                                }
                            }}
                        />
                        <div className="flex justify-between items-center gap-x-3 gap-y-1 flex-wrap">
                            <FormControlLabel control={<Checkbox />} label="Remember me" />
                            <Typography
                                className="text-end"
                                color="primary.main"
                                component={Link}
                                href={'/pages/auth/forgot-password-v1'}
                            >
                                Forgot password?
                            </Typography>
                        </div>
                        <Button fullWidth variant="contained" type="submit">
                            Login
                        </Button>
                        <div className="flex justify-center items-center flex-wrap gap-2">
                            <Typography>New on our platform?</Typography>
                            <Typography component={Link} href={'/pages/auth/register-v1'} color="primary.main">
                                Create an account
                            </Typography>
                        </div>
                        <Divider className="gap-2 text-textPrimary">or</Divider>
                        <div className="flex justify-center items-center gap-1.5">
                            <IconButton className="text-facebook" size="small">
                                <i className="tabler-brand-facebook-filled" />
                            </IconButton>
                            <IconButton className="text-twitter" size="small">
                                <i className="tabler-brand-twitter-filled" />
                            </IconButton>
                            <IconButton className="text-textPrimary" size="small">
                                <i className="tabler-brand-github-filled" />
                            </IconButton>
                            <IconButton className="text-error" size="small">
                                <i className="tabler-brand-google-filled" />
                            </IconButton>
                        </div>
                    </form>
                </CardContent>
            </Card>
        </AuthIllustrationWrapper>
    );
};

export default LoginV1;

// vuexy-admin-v10.11.1/nuxt-version/javascript-version/full-version/pages/pages/authentication/login-v1.vue
<script setup>
import AuthProvider from '@/views/pages/authentication/AuthProvider.vue'
import authV1BottomShape from '@images/svg/auth-v1-bottom-shape.svg?raw'
import authV1TopShape from '@images/svg/auth-v1-top-shape.svg?raw'
import { VNodeRenderer } from '@layouts/components/VNodeRenderer'
import { themeConfig } from '@themeConfig'

definePageMeta({
  layout: 'blank',
  public: true,

})

const form = ref({
  email: '',
  password: '',
  remember: false,
})

const isPasswordVisible = ref(false)
</script>

<template>
  <div class="auth-wrapper d-flex align-center justify-center pa-4">
    <div class="position-relative my-sm-16">
      <!-- 👉 Top shape -->
      <VNodeRenderer
        :nodes="h('div', { innerHTML: authV1TopShape })"
        class="text-primary auth-v1-top-shape d-none d-sm-block"
      />

      <!-- 👉 Bottom shape -->
      <VNodeRenderer
        :nodes="h('div', { innerHTML: authV1BottomShape })"
        class="text-primary auth-v1-bottom-shape d-none d-sm-block"
      />

      <!-- 👉 Auth Card -->
      <VCard
        class="auth-card"
        max-width="460"
        :class="$vuetify.display.smAndUp ? 'pa-6' : 'pa-0'"
      >
        <VCardItem class="justify-center">
          <VCardTitle>
            <NuxtLink to="/">
              <div class="app-logo">
                <VNodeRenderer :nodes="themeConfig.app.logo" />
                <h1 class="app-logo-title">
                  {{ themeConfig.app.title }}
                </h1>
              </div>
            </NuxtLink>
          </VCardTitle>
        </VCardItem>

        <VCardText>
          <h4 class="text-h4 mb-1">
            Welcome to <span class="text-capitalize">{{ themeConfig.app.title }}</span>! 👋🏻
          </h4>
          <p class="mb-0">
            Please sign-in to your account and start the adventure
          </p>
        </VCardText>

        <VCardText>
          <VForm @submit.prevent="() => {}">
            <VRow>
              <!-- email -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.email"
                  autofocus
                  label="Email or Username"
                  type="email"
                  placeholder="johndoe@email.com"
                />
              </VCol>

              <!-- password -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.password"
                  label="Password"
                  placeholder="············"
                  :type="isPasswordVisible ? 'text' : 'password'"
                  autocomplete="password"
                  :append-inner-icon="isPasswordVisible ? 'tabler-eye-off' : 'tabler-eye'"
                  @click:append-inner="isPasswordVisible = !isPasswordVisible"
                />

                <!-- remember me checkbox -->
                <div class="d-flex align-center justify-space-between flex-wrap my-6">
                  <VCheckbox
                    :id="useId()"
                    v-model="form.remember"
                    label="Remember me"
                  />

                  <NuxtLink
                    class="text-primary"
                    :to="{ name: 'pages-authentication-forgot-password-v1' }"
                  >
                    Forgot Password?
                  </NuxtLink>
                </div>

                <!-- login button -->
                <VBtn
                  block
                  type="submit"
                >
                  Login
                </VBtn>
              </VCol>

              <!-- create account -->
              <VCol
                cols="12"
                class="text-body-1 text-center"
              >
                <span class="d-inline-block">
                  New on our platform?
                </span>
                <NuxtLink
                  class="text-primary ms-1 d-inline-block text-body-1"
                  :to="{ name: 'pages-authentication-register-v1' }"
                >
                  Create an account
                </NuxtLink>
              </VCol>

              <VCol
                cols="12"
                class="d-flex align-center"
              >
                <VDivider />
                <span class="mx-4 text-high-emphasis">or</span>
                <VDivider />
              </VCol>

              <!-- auth providers -->
              <VCol
                cols="12"
                class="text-center"
              >
                <AuthProvider />
              </VCol>
            </VRow>
          </VForm>
        </VCardText>
      </VCard>
    </div>
  </div>
</template>

<style lang="scss">
@use "@core/scss/template/pages/page-auth";
</style>
