// src/views/pages/auth/RegisterV1.jsx
'use client';

// React Imports
import { useState } from 'react';

// Next Imports
import Link from 'next/link';

// MUI Imports
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import InputAdornment from '@mui/material/InputAdornment';
import Checkbox from '@mui/material/Checkbox';
import Button from '@mui/material/Button';
import FormControlLabel from '@mui/material/FormControlLabel';
import Divider from '@mui/material/Divider';

// Component Imports
import Logo from '@components/layout/shared/Logo';
import CustomTextField from '@core/components/mui/TextField';

// Styled Component Imports
import AuthIllustrationWrapper from './AuthIllustrationWrapper';

const RegisterV1 = () => {
    // States
    const [isPasswordShown, setIsPasswordShown] = useState(false);

    // Hooks
    const handleClickShowPassword = () => setIsPasswordShown((show) => !show);

    return (
        <AuthIllustrationWrapper>
            <Card className="flex flex-col sm:is-[450px]">
                <CardContent className="sm:!p-12">
                    <Link href={'/'} className="flex justify-center mbe-6">
                        <Logo />
                    </Link>
                    <div className="flex flex-col gap-1 mbe-6">
                        <Typography variant="h4">Adventure starts here 🚀</Typography>
                        <Typography>Make your app management easy and fun!</Typography>
                    </div>
                    <form
                        noValidate
                        autoComplete="off"
                        onSubmit={(e) => e.preventDefault()}
                        className="flex flex-col gap-6"
                    >
                        <CustomTextField autoFocus fullWidth label="Username" placeholder="Enter your username" />
                        <CustomTextField fullWidth label="Email" placeholder="Enter your email" />
                        <CustomTextField
                            fullWidth
                            label="Password"
                            placeholder="············"
                            type={isPasswordShown ? 'text' : 'password'}
                            slotProps={{
                                input: {
                                    endAdornment: (
                                        <InputAdornment position="end">
                                            <IconButton
                                                edge="end"
                                                onClick={handleClickShowPassword}
                                                onMouseDown={(e) => e.preventDefault()}
                                            >
                                                <i className={isPasswordShown ? 'tabler-eye-off' : 'tabler-eye'} />
                                            </IconButton>
                                        </InputAdornment>
                                    )
                                }
                            }}
                        />
                        <FormControlLabel
                            control={<Checkbox />}
                            label={
                                <>
                                    <span>I agree to </span>
                                    <Link className="text-primary" href="/" onClick={(e) => e.preventDefault()}>
                                        privacy policy & terms
                                    </Link>
                                </>
                            }
                        />
                        <Button fullWidth variant="contained" type="submit">
                            Sign Up
                        </Button>
                        <div className="flex justify-center items-center flex-wrap gap-2">
                            <Typography>Already have an account?</Typography>
                            <Typography component={Link} href={'/pages/auth/login-v1'} color="primary.main">
                                Sign in instead
                            </Typography>
                        </div>
                        <Divider className="gap-2 text-textPrimary">or</Divider>
                        <div className="flex justify-center items-center gap-1.5">
                            <IconButton className="text-facebook" size="small">
                                <i className="tabler-brand-facebook-filled" />
                            </IconButton>
                            <IconButton className="text-twitter" size="small">
                                <i className="tabler-brand-twitter-filled" />
                            </IconButton>
                            <IconButton className="text-textPrimary" size="small">
                                <i className="tabler-brand-github-filled" />
                            </IconButton>
                            <IconButton className="text-error" size="small">
                                <i className="tabler-brand-google-filled" />
                            </IconButton>
                        </div>
                    </form>
                </CardContent>
            </Card>
        </AuthIllustrationWrapper>
    );
};

export default RegisterV1;

// vuexy-admin-v10.11.1/nuxt-version/javascript-version/full-version/pages/pages/authentication/register-v1.vue
<script setup>
import AuthProvider from '@/views/pages/authentication/AuthProvider.vue'
import authV1BottomShape from '@images/svg/auth-v1-bottom-shape.svg?raw'
import authV1TopShape from '@images/svg/auth-v1-top-shape.svg?raw'
import { VNodeRenderer } from '@layouts/components/VNodeRenderer'
import { themeConfig } from '@themeConfig'

definePageMeta({
  layout: 'blank',
  public: true,

})

const form = ref({
  username: '',
  email: '',
  password: '',
  privacyPolicies: false,
})

const isPasswordVisible = ref(false)
</script>

<template>
  <div class="auth-wrapper d-flex align-center justify-center pa-4">
    <div class="position-relative my-sm-16">
      <!-- 👉 Top shape -->
      <VNodeRenderer
        :nodes="h('div', { innerHTML: authV1TopShape })"
        class="text-primary auth-v1-top-shape d-none d-sm-block"
      />

      <!-- 👉 Bottom shape -->
      <VNodeRenderer
        :nodes="h('div', { innerHTML: authV1BottomShape })"
        class="text-primary auth-v1-bottom-shape d-none d-sm-block"
      />

      <!-- 👉 Auth card -->
      <VCard
        class="auth-card"
        max-width="460"
        :class="$vuetify.display.smAndUp ? 'pa-6' : 'pa-0'"
      >
        <VCardItem class="justify-center">
          <VCardTitle>
            <NuxtLink to="/">
              <div class="app-logo">
                <VNodeRenderer :nodes="themeConfig.app.logo" />
                <h1 class="app-logo-title">
                  {{ themeConfig.app.title }}
                </h1>
              </div>
            </NuxtLink>
          </VCardTitle>
        </VCardItem>

        <VCardText>
          <h4 class="text-h4 mb-1">
            Adventure starts here 🚀
          </h4>
          <p class="mb-0">
            Make your app management easy and fun!
          </p>
        </VCardText>

        <VCardText>
          <VForm @submit.prevent="() => {}">
            <VRow>
              <!-- Username -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.username"
                  autofocus
                  label="Username"
                  placeholder="Johndoe"
                />
              </VCol>
              <!-- email -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.email"
                  label="Email"
                  type="email"
                  placeholder="johndoe@email.com"
                />
              </VCol>

              <!-- password -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.password"
                  label="Password"
                  placeholder="············"
                  :type="isPasswordVisible ? 'text' : 'password'"
                  autocomplete="password"
                  :append-inner-icon="isPasswordVisible ? 'tabler-eye-off' : 'tabler-eye'"
                  @click:append-inner="isPasswordVisible = !isPasswordVisible"
                />

                <div class="d-flex align-center my-6">
                  <VCheckbox
                    id="privacy-policy"
                    v-model="form.privacyPolicies"
                    inline
                  />
                  <VLabel
                    for="privacy-policy"
                    style="opacity: 1;"
                  >
                    <span class="me-1 text-high-emphasis">I agree to</span>
                    <a
                      href="javascript:void(0)"
                      class="text-primary"
                    >privacy policy & terms</a>
                  </VLabel>
                </div>

                <VBtn
                  block
                  type="submit"
                >
                  Sign up
                </VBtn>
              </VCol>

              <!-- login instead -->
              <VCol
                cols="12"
                class="text-center text-base"
              >
                <span>Already have an account?</span>
                <NuxtLink
                  class="text-primary ms-1"
                  :to="{ name: 'pages-authentication-login-v1' }"
                >
                  Sign in instead
                </NuxtLink>
              </VCol>

              <VCol
                cols="12"
                class="d-flex align-center"
              >
                <VDivider />
                <span class="mx-4">or</span>
                <VDivider />
              </VCol>

              <!-- auth providers -->
              <VCol
                cols="12"
                class="text-center"
              >
                <AuthProvider />
              </VCol>
            </VRow>
          </VForm>
        </VCardText>
      </VCard>
    </div>
  </div>
</template>

<style lang="scss">
@use "@core/scss/template/pages/page-auth";
</style>
