// vuexy-admin-v10.11.1/nuxt-version/javascript-version/full-version/pages/register.vue
<script setup>
import { VForm } from 'vuetify/components/VForm'
import AuthProvider from '@/views/pages/authentication/AuthProvider.vue'
import { VNodeRenderer } from '@layouts/components/VNodeRenderer'
import { themeConfig } from '@themeConfig'
import authV2RegisterIllustrationBorderedDark from '@images/pages/auth-v2-register-illustration-bordered-dark.png'
import authV2RegisterIllustrationBorderedLight from '@images/pages/auth-v2-register-illustration-bordered-light.png'
import authV2RegisterIllustrationDark from '@images/pages/auth-v2-register-illustration-dark.png'
import authV2RegisterIllustrationLight from '@images/pages/auth-v2-register-illustration-light.png'
import authV2MaskDark from '@images/pages/misc-mask-dark.png'
import authV2MaskLight from '@images/pages/misc-mask-light.png'

const imageVariant = useGenerateImageVariant(authV2RegisterIllustrationLight, authV2RegisterIllustrationDark, authV2RegisterIllustrationBorderedLight, authV2RegisterIllustrationBorderedDark, true)
const authThemeMask = useGenerateImageVariant(authV2MaskLight, authV2MaskDark)

definePageMeta({
  layout: 'blank',
  unauthenticatedOnly: true,

})

const form = ref({
  username: '',
  email: '',
  password: '',
  privacyPolicies: false,
})

const isPasswordVisible = ref(false)
</script>

<template>
  <NuxtLink to="/">
    <div class="auth-logo d-flex align-center gap-x-3">
      <VNodeRenderer :nodes="themeConfig.app.logo" />
      <h1 class="auth-title">
        {{ themeConfig.app.title }}
      </h1>
    </div>
  </NuxtLink>

  <VRow
    no-gutters
    class="auth-wrapper bg-surface"
  >
    <VCol
      md="8"
      class="d-none d-md-flex"
    >
      <div class="position-relative bg-background w-100 me-0">
        <div
          class="d-flex align-center justify-center w-100 h-100"
          style="padding-inline: 100px;"
        >
          <VImg
            max-width="500"
            :src="imageVariant"
            class="auth-illustration mt-16 mb-2"
          />
        </div>

        <img
          class="auth-footer-mask"
          :src="authThemeMask"
          alt="auth-footer-mask"
          height="280"
          width="100"
        >
      </div>
    </VCol>

    <VCol
      cols="12"
      md="4"
      class="auth-card-v2 d-flex align-center justify-center"
      style="background-color: rgb(var(--v-theme-surface));"
    >
      <VCard
        flat
        :max-width="500"
        class="mt-12 mt-sm-0 pa-4"
      >
        <VCardText>
          <h4 class="text-h4 mb-1">
            Adventure starts here 🚀
          </h4>
          <p class="mb-0">
            Make your app management easy and fun!
          </p>
        </VCardText>

        <VCardText>
          <VForm @submit.prevent="() => {}">
            <VRow>
              <!-- Username -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.username"
                  :rules="[requiredValidator]"
                  autofocus
                  label="Username"
                  placeholder="Johndoe"
                />
              </VCol>

              <!-- email -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.email"
                  :rules="[requiredValidator, emailValidator]"
                  label="Email"
                  type="email"
                  placeholder="johndoe@email.com"
                />
              </VCol>

              <!-- password -->
              <VCol cols="12">
                <AppTextField
                  v-model="form.password"
                  :rules="[requiredValidator]"
                  label="Password"
                  placeholder="············"
                  :type="isPasswordVisible ? 'text' : 'password'"
                  autocomplete="password"
                  :append-inner-icon="isPasswordVisible ? 'tabler-eye-off' : 'tabler-eye'"
                  @click:append-inner="isPasswordVisible = !isPasswordVisible"
                />

                <div class="d-flex align-center my-6">
                  <VCheckbox
                    id="privacy-policy"
                    v-model="form.privacyPolicies"
                    inline
                  />
                  <VLabel
                    for="privacy-policy"
                    style="opacity: 1;"
                  >
                    <span class="me-1 text-high-emphasis">I agree to</span>
                    <a
                      href="javascript:void(0)"
                      class="text-primary"
                    >privacy policy & terms</a>
                  </VLabel>
                </div>

                <VBtn
                  block
                  type="submit"
                >
                  Sign up
                </VBtn>
              </VCol>

              <!-- create account -->
              <VCol
                cols="12"
                class="text-center text-base"
              >
                <span class="d-inline-block">Already have an account?</span>
                <NuxtLink
                  class="text-primary ms-1 d-inline-block"
                  :to="{ name: 'login' }"
                >
                  Sign in instead
                </NuxtLink>
              </VCol>

              <VCol
                cols="12"
                class="d-flex align-center"
              >
                <VDivider />
                <span class="mx-4">or</span>
                <VDivider />
              </VCol>

              <!-- auth providers -->
              <VCol
                cols="12"
                class="text-center"
              >
                <AuthProvider />
              </VCol>
            </VRow>
          </VForm>
        </VCardText>
      </VCard>
    </VCol>
  </VRow>
</template>

<style lang="scss">
@use "@core/scss/template/pages/page-auth";
</style>

// src/views/Register.jsx
'use client';

// React Imports
import { useState } from 'react';

// Next Imports
import Link from 'next/link';

// MUI Imports
import useMediaQuery from '@mui/material/useMediaQuery';
import { styled, useTheme } from '@mui/material/styles';
import Typography from '@mui/material/Typography';
import IconButton from '@mui/material/IconButton';
import InputAdornment from '@mui/material/InputAdornment';
import Checkbox from '@mui/material/Checkbox';
import Button from '@mui/material/Button';
import FormControlLabel from '@mui/material/FormControlLabel';
import Divider from '@mui/material/Divider';

// Third-party Imports
import classnames from 'classnames';

// Component Imports
import Logo from '@components/layout/shared/Logo';
import CustomTextField from '@core/components/mui/TextField';

// Hook Imports
import { useImageVariant } from '@core/hooks/useImageVariant';
import { useSettings } from '@core/hooks/useSettings';

// Styled Custom Components
const RegisterIllustration = styled('img')(({ theme }) => ({
    zIndex: 2,
    blockSize: 'auto',
    maxBlockSize: 600,
    maxInlineSize: '100%',
    margin: theme.spacing(12),
    [theme.breakpoints.down(1536)]: {
        maxBlockSize: 550
    },
    [theme.breakpoints.down('lg')]: {
        maxBlockSize: 450
    }
}));

const MaskImg = styled('img')({
    blockSize: 'auto',
    maxBlockSize: 345,
    inlineSize: '100%',
    position: 'absolute',
    insetBlockEnd: 0,
    zIndex: -1
});

const Register = ({ mode }) => {
    // States
    const [isPasswordShown, setIsPasswordShown] = useState(false);

    // Vars
    const darkImg = '/images/pages/auth-mask-dark.png';
    const lightImg = '/images/pages/auth-mask-light.png';
    const darkIllustration = '/images/illustrations/auth/v2-register-dark.png';
    const lightIllustration = '/images/illustrations/auth/v2-register-light.png';
    const borderedDarkIllustration = '/images/illustrations/auth/v2-register-dark-border.png';
    const borderedLightIllustration = '/images/illustrations/auth/v2-register-light-border.png';

    // Hooks
    const { settings } = useSettings();
    const theme = useTheme();
    const hidden = useMediaQuery(theme.breakpoints.down('md'));
    const authBackground = useImageVariant(mode, lightImg, darkImg);

    const characterIllustration = useImageVariant(
        mode,
        lightIllustration,
        darkIllustration,
        borderedLightIllustration,
        borderedDarkIllustration
    );

    const handleClickShowPassword = () => setIsPasswordShown((show) => !show);

    return (
        <div className="flex bs-full justify-center">
            <div
                className={classnames(
                    'flex bs-full items-center justify-center flex-1 min-bs-[100dvh] relative p-6 max-md:hidden',
                    {
                        'border-ie': settings.skin === 'bordered'
                    }
                )}
            >
                <RegisterIllustration src={characterIllustration} alt="character-illustration" />
                {!hidden && <MaskImg alt="mask" src={authBackground} />}
            </div>
            <div className="flex justify-center items-center bs-full bg-backgroundPaper !min-is-full p-6 md:!min-is-[unset] md:p-12 md:is-[480px]">
                <Link
                    href={'/login'}
                    className="absolute block-start-5 sm:block-start-[33px] inline-start-6 sm:inline-start-[38px]"
                >
                    <Logo />
                </Link>
                <div className="flex flex-col gap-6 is-full sm:is-auto md:is-full sm:max-is-[400px] md:max-is-[unset] mbs-8 sm:mbs-11 md:mbs-0">
                    <div className="flex flex-col gap-1">
                        <Typography variant="h4">Adventure starts here 🚀</Typography>
                        <Typography>Make your app management easy and fun!</Typography>
                    </div>
                    <form
                        noValidate
                        autoComplete="off"
                        onSubmit={(e) => e.preventDefault()}
                        className="flex flex-col gap-6"
                    >
                        <CustomTextField autoFocus fullWidth label="Username" placeholder="Enter your username" />
                        <CustomTextField fullWidth label="Email" placeholder="Enter your email" />
                        <CustomTextField
                            fullWidth
                            label="Password"
                            placeholder="············"
                            type={isPasswordShown ? 'text' : 'password'}
                            slotProps={{
                                input: {
                                    endAdornment: (
                                        <InputAdornment position="end">
                                            <IconButton
                                                edge="end"
                                                onClick={handleClickShowPassword}
                                                onMouseDown={(e) => e.preventDefault()}
                                            >
                                                <i className={isPasswordShown ? 'tabler-eye-off' : 'tabler-eye'} />
                                            </IconButton>
                                        </InputAdornment>
                                    )
                                }
                            }}
                        />
                        <FormControlLabel
                            control={<Checkbox />}
                            label={
                                <>
                                    <span>I agree to </span>
                                    <Link className="text-primary" href="/" onClick={(e) => e.preventDefault()}>
                                        privacy policy & terms
                                    </Link>
                                </>
                            }
                        />
                        <Button fullWidth variant="contained" type="submit">
                            Sign Up
                        </Button>
                        <div className="flex justify-center items-center flex-wrap gap-2">
                            <Typography>Already have an account?</Typography>
                            <Typography component={Link} href={'/login'} color="primary.main">
                                Sign in instead
                            </Typography>
                        </div>
                        <Divider className="gap-2">or</Divider>
                        <div className="flex justify-center items-center gap-1.5">
                            <IconButton className="text-facebook" size="small">
                                <i className="tabler-brand-facebook-filled" />
                            </IconButton>
                            <IconButton className="text-twitter" size="small">
                                <i className="tabler-brand-twitter-filled" />
                            </IconButton>
                            <IconButton className="text-textPrimary" size="small">
                                <i className="tabler-brand-github-filled" />
                            </IconButton>
                            <IconButton className="text-error" size="small">
                                <i className="tabler-brand-google-filled" />
                            </IconButton>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
};

export default Register;
